name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 📤 Copy files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "~/kannadanibba"

      - name: 🚀 SSH into VPS and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: NEXT_PUBLIC_API_URL
          script: |
            export NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
            cd ~/kannadanibba
            docker-compose down --volumes --remove-orphans || true
            docker-compose build --no-cache
            docker-compose up -d
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.API_URL }}
